name: Deploy

on:
  push:
    branches:
      - master

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16.x

      - name: Installling dependencies
        run: npm install

      - name: ESLint check
        run: npx eslint --ignore-path .gitignore .

      - name: Test
        run: npm run test

      # - name: Initialize CodeQL
      #   uses: github/codeql-action/init@v1
      #   with:
      #     languages: javascript

      # - name: Perform CodeQL Analysis
      #   uses: github/codeql-action/analyze@v1

      # - name: Send coverage report to Codecov
      #   uses: codecov/codecov-action@v2

  # cd:
  #   name: CD
  #   needs: ci
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 15
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - uses: superfly/flyctl-actions@master
  #       env:
  #         FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  #       with:
  #         args: "deploy"

  #     - name: Create Sentry release
  #       uses: getsentry/action-release@v1
  #       env:
  #         SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_TOKEN }}
  #         SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
  #         SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
  #       with:
  #         environment: production
  #         set_commits: skip
  #         version: ${{ github.sha }}
